version: "2"
services:
    py:
        extends:
            file: docker-compose.yml
            service: py
        depends_on:
            - cs1
            - cs2
    cs1:
        image: cassandra:3
        restart: on-failure:2
        
        # suppose default cpu period is 100ms, this set 25% CPU limit
        cpu_quota: 25000
        mem_limit: 256M
        memswap_limit: 0M
        environment:
            - CASSANDRA_CLUSTER_NAME=app
            - CASSANDRA_DC=dc1
        # volumes:
        #    - tmp/cs1:/var/lib/cassandra
    cs2:
        extends:
            service: cs1
        environment:
            - CASSANDRA_SEEDS=cs1