version: "2"
services:
    tool: &common
        image: tokit/tokit:0.7
        command: python3 -m smtpd -n -c DebuggingServer 0.0.0.0:25
        restart: on-failure:1
        mem_limit: 128M
        memswap_limit: 0M
        cpu_quota: 25000
        tty: false
        expose:
            - 25
    py:
        <<: *common
        image: tokit/tokit:0.7
        working_dir: /app/src
        command: /usr/local/bin/python3 /app/src/app.py --host=0.0.0.0 --port=9000 --env=docker
        expose:
            - "9000"
        volumes:
            - .:/app
    web:
        <<: *common
        image: nginx:1.10-alpine
        volumes:
            - ./config/nginx.conf:/mnt/nginx.conf
            - ./tmp/nginx_log/:/var/log/nginx/
        command: nginx -g 'daemon off;' -c /mnt/nginx.conf
        links:
            - py
        ports:
            - "8000:80"