version: "2"
services:
    py:
        build: .
        working_dir: /app/src
        restart: on-failure:3
        command: /usr/local/bin/python3 /app/src/app.py --host=0.0.0.0 --port=9000 --env=docker
        expose:
            - "9000"
        volumes:
            - .:/app
        mem_limit: 128M
    web:
        image: nginx:1.10-alpine
        restart: on-failure:2
        container_name: web
        volumes:
            - ./config/nginx:/mnt/conf
            
            - ./config/nginx/docker.conf:/etc/nginx/nginx.conf
        command: /bin/bash /mnt/conf/cmd.sh
        links:
            - py
        ports:
            - "8000:80"
    mail:
        image: giang/tokit:1
        command: python3 -m smtpd -n -c DebuggingServer 0.0.0.0:25
        expose:
            - 25