version: "2"
services:
    mail: &common
        image: tokit/tokit:0.7
        command: python3 -m smtpd -n -c DebuggingServer 0.0.0.0:25
        restart: on-failure:1
        mem_limit: 128M
        memswap_limit: 0M
        cpu_quota: 25000
        tty: false
        expose:
            - 25
    py0: &py_
        <<: *common
        image: tokit/tokit:0.7
        working_dir: /app/src
        command: /bin/sh /app/update.sh
        environment:
            - TOKIT_VER=master
            - PORT=9000
        expose:
            - "9000"
        volumes:
            - .:/app
    py1:
        <<: *py_
        environment:
            - TOKIT_VER=master
            - PORT=9001
        expose:
            - "9001"
    web:
        <<: *common
        image: nginx:1.10-alpine
        volumes:
            - ./config/nginx.conf:/mnt/nginx.conf
            - ./tmp/nginx_log/:/var/log/nginx/
        command: nginx -g 'daemon off;' -c /mnt/nginx.conf
        links:
            - py0
            - py1
        ports:
            - "8000:80"